AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

# Disable false positives for service lifecycle methods
Naming/PredicateMethod:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/cli/**/*'  # CLI modules use class_eval blocks

Metrics/MethodLength:
  Exclude:
    - 'lib/cli/**/*'
    - 'lib/docker_manager.rb'  # Service status method is complex by nature
    - 'lib/config_validator.rb'  # Complex validation logic
    - 'lib/security_manager.rb'  # Security methods need comprehensive logic

Metrics/AbcSize:
  Exclude:
    - 'lib/cli/**/*'
    - 'lib/config_validator.rb'
    - 'lib/security_manager.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/docker_manager.rb'  # Core orchestration class is complex
    - 'lib/config_validator.rb'  # Comprehensive validation logic
    - 'lib/security_manager.rb'  # Extensive security functionality

Metrics/ModuleLength:
  Exclude:
    - 'lib/cli/**/*'  # CLI command modules are inherently large

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

# Format strings are acceptable for table output
Style/FormatStringToken:
  Exclude:
    - 'lib/cli/status_commands.rb'