---
:tcf_quickstart:
  :version: 0.1.0
  :enhanced_at: '2025-08-27T15:23:03-04:00'
  :options:
    :tech_stack: ruby
    :domain: web
    :private: false
    :license: mit
    :force: true
    :backup: false
